from test import db, Symptom, app

symptoms_data = [
    {'name': 'energized', 'tip': 'Engage in physical activities to utilize your energy.'},
    {'name': 'exhausted', 'tip': 'Ensure you get enough rest and stay hydrated.'},
    {'name': 'anxiety', 'tip': 'Practice mindfulness and meditation to manage anxiety.'},
    {'name': 'calm', 'tip': 'Maintain your calmness with regular meditation.'},
    {'name': 'happy', 'tip': 'Share your happiness with others to spread positivity.'},
    {'name': 'irritable', 'tip': 'Take deep breaths and try to relax.'},
    {'name': 'mood swings', 'tip': 'Keep a mood journal to track and manage your emotions.'},
    {'name': 'sad', 'tip': 'Talk to a friend or engage in a hobby you enjoy.'},
    {'name': 'creative', 'tip': 'Channel your creativity into a project or artwork.'},
    {'name': 'unmotivated', 'tip': 'Set small, achievable goals to regain motivation.'},
    {'name': 'overly self-critical', 'tip': 'Practice self-compassion and positive affirmations.'},
    {'name': 'unfocused', 'tip': 'Take short breaks and minimize distractions.'},
    {'name': 'brain fog', 'tip': 'Stay hydrated and take regular breaks.'},
    {'name': 'depressed', 'tip': 'Seek support from friends, family, or a mental health professional.'},
    {'name': 'panic', 'tip': 'Practice deep breathing exercises to calm yourself.'},
    {'name': 'rage', 'tip': 'Engage in physical activities to release pent-up anger.'},
    {'name': 'salty', 'tip': 'Balance your cravings with healthy snacks.'},
    {'name': 'sweet', 'tip': 'Opt for natural sugars like fruits.'},
    {'name': 'carbs', 'tip': 'Choose whole grains over refined carbs.'},
    {'name': 'fried things', 'tip': 'Limit fried foods and opt for healthier cooking methods.'},
    {'name': 'fountain soda', 'tip': 'Replace soda with sparkling water or herbal tea.'},
    {'name': 'extra sauce', 'tip': 'Use sauces in moderation to avoid excess calories.'},
    {'name': 'greens', 'tip': 'Incorporate a variety of greens into your meals.'},
    {'name': 'meat', 'tip': 'Choose lean meats and balance with vegetables.'},
    {'name': 'fruit', 'tip': 'Enjoy a variety of fruits for different nutrients.'},
    {'name': 'alone time', 'tip': 'Take time for self-care and reflection.'},
    {'name': 'deep talk', 'tip': 'Engage in meaningful conversations with loved ones.'},
    {'name': 'headache', 'tip': 'Stay hydrated and rest in a dark, quiet room.'},
    {'name': 'cramps', 'tip': 'Apply heat and practice gentle stretching.'},
    {'name': 'low appetite', 'tip': 'Eat small, frequent meals and stay hydrated.'},
    {'name': 'increased appetite', 'tip': 'Choose healthy snacks and balanced meals.'},
    {'name': 'acne', 'tip': 'Maintain a skincare routine and stay hydrated.'},
    {'name': 'migraine', 'tip': 'Rest in a dark, quiet room and stay hydrated.'},
    {'name': 'ovulation pain', 'tip': 'Apply heat and rest as needed.'},
    {'name': 'back pain', 'tip': 'Practice good posture and gentle stretching.'},
    {'name': 'nausea', 'tip': 'Eat small, frequent meals and stay hydrated.'},
    {'name': 'insomnia', 'tip': 'Practice good sleep hygiene and relaxation techniques.'},
    {'name': 'yeast infection', 'tip': 'Maintain good hygiene and consult a healthcare provider.'},
    {'name': 'confirmed UTI', 'tip': 'Stay hydrated and consult a healthcare provider.'},
    {'name': 'joint pain', 'tip': 'Engage in low-impact exercises and stay active.'},
    {'name': 'night sweats', 'tip': 'Keep your bedroom cool and wear breathable fabrics.'},
    {'name': 'light', 'tip': 'Monitor your flow and stay hydrated.'},
    {'name': 'medium', 'tip': 'Maintain good hygiene and stay hydrated.'},
    {'name': 'heavy', 'tip': 'Monitor your flow and consult a healthcare provider if needed.'},
    {'name': 'crime scene', 'tip': 'Consult a healthcare provider if you experience excessive bleeding.'},
    {'name': 'dark purple with clots', 'tip': 'Monitor your flow and consult a healthcare provider if needed.'},
    {'name': 'pale pink and watery', 'tip': 'Monitor your flow and stay hydrated.'},
    {'name': 'brownish', 'tip': 'Monitor your flow and stay hydrated.'},
    {'name': 'spotting', 'tip': 'Monitor your flow and consult a healthcare provider if needed.'},
    {'name': 'nothing', 'tip': 'Monitor your cycle and consult a healthcare provider if needed.'},
    {'name': 'watery', 'tip': 'Monitor your cervical mucus and stay hydrated.'},
    {'name': 'egg white (ovulating)', 'tip': 'Monitor your cervical mucus and stay hydrated.'},
    {'name': 'creamy', 'tip': 'Monitor your cervical mucus and stay hydrated.'},
    {'name': 'sticky', 'tip': 'Monitor your cervical mucus and stay hydrated.'},
    {'name': 'none (dry)', 'tip': 'Monitor your cervical mucus and stay hydrated.'},
    {'name': 'meditation', 'tip': 'Practice regularly to maintain mental well-being.'},
    {'name': 'cardio', 'tip': 'Engage in regular cardio exercises for overall health.'},
    {'name': 'weight training', 'tip': 'Incorporate weight training into your fitness routine.'},
    {'name': 'dance party', 'tip': 'Enjoy dancing as a fun way to stay active.'},
    {'name': 'massage', 'tip': 'Schedule regular massages for relaxation and muscle relief.'},
    {'name': 'netflix', 'tip': 'Take breaks and avoid binge-watching for long periods.'},
    {'name': 'shopping', 'tip': 'Shop mindfully and avoid impulsive purchases.'},
    {'name': 'caffeine', 'tip': 'Limit caffeine intake to avoid dependency.'},
    {'name': 'alcohol', 'tip': 'Consume alcohol in moderation and stay hydrated.'},
    {'name': 'nicotine', 'tip': 'Seek support to quit smoking and improve health.'},
    {'name': 'adderall[ADHD]', 'tip': 'Follow your healthcare provider\'s instructions for medication use.'},
    {'name': 'benzos[Anxiety]', 'tip': 'Follow your healthcare provider\'s instructions for medication use.'},
    {'name': 'travel', 'tip': 'Plan ahead and stay organized to reduce travel stress.'},
    {'name': 'sickness', 'tip': 'Rest and stay hydrated to recover from illness.'},
    {'name': 'stress', 'tip': 'Practice stress management techniques like meditation and exercise.'},
    {'name': 'injury', 'tip': 'Follow your healthcare provider\'s instructions for recovery.'},
    {'name': '+ ovulation test', 'tip': 'Monitor your cycle and plan accordingly.'},
    {'name': '- ovulation test', 'tip': 'Monitor your cycle and consult a healthcare provider if needed.'},
]

with app.app_context():
    db.create_all()  # Ensure the database tables are created
    for symptom_data in symptoms_data:
        symptom = Symptom(name=symptom_data['name'], tip=symptom_data['tip'])
        db.session.add(symptom)
    db.session.commit()